require 'ecm/frontend'
require 'ecm/admin'
require 'ecm/cms/pages/railtie'
# require 'ecm/cms/pages/layout_resolver'
require 'ecm/cms/pages/template_resolver'
# require 'ecm/cms/pages/partial_resolver'
